name: Build RedVelvet APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          android/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make Gradle wrapper executable
      run: chmod +x android/gradlew
      
    - name: Clean and build APK
      run: |
        cd android
        ./gradlew clean
        ./gradlew assembleDebug
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: redvelvet-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Create GitHub release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: build-${{ github.run_number }}
        name: RedVelvet APK Build ${{ github.run_number }}
        body: |
          ## RedVelvet AI Companion APK - Ready to Install
          
          ✅ **Java compilation errors fixed**  
          ✅ **Server live at https://red-velvet-connection.replit.app**  
          ✅ **AI responses and diamond tracking working**  
          ✅ **Back button navigation crash-proof**  
          
          ### Installation Instructions
          1. Download `app-debug.apk` from this release
          2. Enable "Unknown sources" in Android settings
          3. Install APK and enjoy your AI companion
          
          ### Verified Features
          - Device-based diamond tracking (25 diamonds welcome bonus)
          - AI chat with automatic diamond deduction
          - WhatsApp-style mobile interface
          - Crash-proof back button navigation
        files: android/app/build/outputs/apk/debug/app-debug.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}